import imdb
import time

ia = imdb.Cinemagoer()

actionTop50 = ia.get_top50_movies_by_genres("Action")
time.sleep(30)
adventureTop50 = ia.get_top50_movies_by_genres("Adventure")
time.sleep(30)
animationTop50 = ia.get_top50_movies_by_genres("Animation")
time.sleep(30)
biographyTop50 = ia.get_top50_movies_by_genres("Biography")
time.sleep(30)
comedyTop50 = ia.get_top50_movies_by_genres("Comedy")
time.sleep(30)
crimeTop50 = ia.get_top50_movies_by_genres("Crime")
time.sleep(30)
documentaryTop50 = ia.get_top50_movies_by_genres("Documentary")
time.sleep(30)
dramaTop50 = ia.get_top50_movies_by_genres("Drama")
time.sleep(30)
familyTop50 = ia.get_top50_movies_by_genres("Family")
time.sleep(30)
fantasyTop50 = ia.get_top50_movies_by_genres("Fantasy")
time.sleep(30)
noirTop50 = ia.get_top50_movies_by_genres("Film-Noir")
time.sleep(30)
historyTop50 = ia.get_top50_movies_by_genres("History")
time.sleep(30)
horrorTop50 = ia.get_top50_movies_by_genres("Horror")
time.sleep(30)
musicTop50 = ia.get_top50_movies_by_genres("Music")
time.sleep(30)
musicalTop50 = ia.get_top50_movies_by_genres("Musical")
time.sleep(30)
mysteryTop50 = ia.get_top50_movies_by_genres("Mystery")
time.sleep(30)
romanceTop50 = ia.get_top50_movies_by_genres("Romance")
time.sleep(30)
scifiTop50 = ia.get_top50_movies_by_genres("Sci-Fi")
time.sleep(30)
shortTop50 = ia.get_top50_movies_by_genres("Short")
time.sleep(30)
sportTop50 = ia.get_top50_movies_by_genres("Sport")
time.sleep(30)
thrillerTop50 = ia.get_top50_movies_by_genres("Thriller")
time.sleep(30)
warTop50 = ia.get_top50_movies_by_genres("War")
time.sleep(30)
westernTop50 = ia.get_top50_movies_by_genres("Western")
time.sleep(30)


top = ia.get_top250_movies()
pop = ia.get_popular100_movies()